In [4]:
import pandas as pd
df = pd.read_csv('sentiment.csv', encoding='latin1')
print(df.columns)
print(df.head(5))

Index(['textID', 'text', 'sentiment', 'Time of Tweet', 'Age of User',
       'Country', 'Population -2020', 'Land Area (Km²)', 'Density (P/Km²)'],
      dtype='str')
       textID                                               text sentiment  \
0  f87dea47db  Last session of the day  http://twitpic.com/67ezh   neutral
1  96d74cb729   Shanghai is also really exciting (precisely -...  positive
2  eee518ae67  Recession hit Veronique Branquinho, she has to...  negative
3  01082688c6                                        happy bday!  positive
4  33987a8ee5             http://twitpic.com/4w75p - I like it!!  positive

  Time of Tweet Age of User      Country  Population -2020  Land Area (Km²)  \
0       morning        0-20  Afghanistan        38928346.0         652860.0
1          noon       21-30      Albania         2877797.0          27400.0
2         night       31-45      Algeria        43851044.0        2381740.0
3       morning       46-60      Andorra           77265.0            470.0
4          noon       60-70       Angola        32866272.0        1246700.0

   Density (P/Km²)
0             60.0
1            105.0
2             18.0
3            164.0
4             26.0

In [5]:
df.isnull().sum()
df

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0
...,...,...,...,...,...,...,...,...,...
4810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df=df.dropna()
df

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0
...,...,...,...,...,...,...,...,...,...
3529,e5f0e6ef4b,"its at 3 am, im very tired but i can`t sleep ...",negative,noon,21-30,Nicaragua,6624554.0,120340.0,55.0
3530,416863ce47,All alone in this old house again. Thanks for...,positive,night,31-45,Niger,24206644.0,1266700.0,19.0
3531,6332da480c,I know what you mean. My little dog is sinkin...,negative,morning,46-60,Nigeria,206139589.0,910770.0,226.0
3532,df1baec676,_sutra what is your next youtube video gonna b...,positive,noon,60-70,North Korea,25778816.0,120410.0,214.0
3533,469e15c5a8,http://twitpic.com/4woj2 - omgssh ang cute n...,positive,night,70-100,North Macedonia,2083374.0,25220.0,83.0

In [7]:
df.isnull().sum()
df

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0
...,...,...,...,...,...,...,...,...,...
3529,e5f0e6ef4b,"its at 3 am, im very tired but i can`t sleep ...",negative,noon,21-30,Nicaragua,6624554.0,120340.0,55.0
3530,416863ce47,All alone in this old house again. Thanks for...,positive,night,31-45,Niger,24206644.0,1266700.0,19.0
3531,6332da480c,I know what you mean. My little dog is sinkin...,negative,morning,46-60,Nigeria,206139589.0,910770.0,226.0
3532,df1baec676,_sutra what is your next youtube video gonna b...,positive,noon,60-70,North Korea,25778816.0,120410.0,214.0
3533,469e15c5a8,http://twitpic.com/4woj2 - omgssh ang cute n...,positive,night,70-100,North Macedonia,2083374.0,25220.0,83.0

In [8]:
import pandas as pd
import re

In [9]:
def clean_text(text):
    text = str(text).lower()  
    text = re.sub(r'http\S+', '', text)  
    text = re.sub(r'[^a-zA-Z\s]', '', text)  
    text = re.sub(r'\s+', ' ', text).strip()  
    return text
clean_text('This is a SAMPLE CLEANED TEST check once @#@^@%&@%#%@$&@^')

'this is a sample cleaned test check once'

In [10]:
df['text']=df['text'].apply(clean_text)
df

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,last session of the day,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,shanghai is also really exciting precisely sky...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,recession hit veronique branquinho she has to ...,negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,i like it,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0
...,...,...,...,...,...,...,...,...,...
3529,e5f0e6ef4b,its at am im very tired but i cant sleep but i...,negative,noon,21-30,Nicaragua,6624554.0,120340.0,55.0
3530,416863ce47,all alone in this old house again thanks for t...,positive,night,31-45,Niger,24206644.0,1266700.0,19.0
3531,6332da480c,i know what you mean my little dog is sinking ...,negative,morning,46-60,Nigeria,206139589.0,910770.0,226.0
3532,df1baec676,sutra what is your next youtube video gonna be...,positive,noon,60-70,North Korea,25778816.0,120410.0,214.0
3533,469e15c5a8,omgssh ang cute ng bby,positive,night,70-100,North Macedonia,2083374.0,25220.0,83.0

In [11]:
df = df[df['text'].str.strip() != '']
df

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,last session of the day,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,shanghai is also really exciting precisely sky...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,recession hit veronique branquinho she has to ...,negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,i like it,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0
...,...,...,...,...,...,...,...,...,...
3529,e5f0e6ef4b,its at am im very tired but i cant sleep but i...,negative,noon,21-30,Nicaragua,6624554.0,120340.0,55.0
3530,416863ce47,all alone in this old house again thanks for t...,positive,night,31-45,Niger,24206644.0,1266700.0,19.0
3531,6332da480c,i know what you mean my little dog is sinking ...,negative,morning,46-60,Nigeria,206139589.0,910770.0,226.0
3532,df1baec676,sutra what is your next youtube video gonna be...,positive,noon,60-70,North Korea,25778816.0,120410.0,214.0
3533,469e15c5a8,omgssh ang cute ng bby,positive,night,70-100,North Macedonia,2083374.0,25220.0,83.0

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:

vectorizer = TfidfVectorizer(max_features=5000)  # limit features to 5000 words
X = vectorizer.fit_transform(df['text'])
y = df['sentiment']
y

0        neutral
1       positive
2       negative
3       positive
4       positive
          ...
3529    negative
3530    positive
3531    negative
3532    positive
3533    positive
Name: sentiment, Length: 3533, dtype: str

In [14]:
print(X.shape)
print(y.shape)

(3533, 5000)
(3533,)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [17]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [18]:
#TELLS ME HOW GOOD MY MODEL IS 
accuracy = model.score(X_test, y_test)
print("Model Accuracy: {:.2f}%".format(accuracy))

Model Accuracy: 0.56%

In [ ]:
# NEW SENTENCE TO PREDICT
sentence = ["I am very happy today!"]
sentence = [clean_text(s) for s in sentence]
# CONVERT TO NUMBERS
sentence_vec = vectorizer.transform(sentence)
prediction = model.predict(sentence_vec)
print("Predicted Emotion:", prediction[0])

Predicted Emotion: positive

In [21]:
def predict_emotion(sentence):
    sentence = clean_text(sentence)
    sentence_vec = vectorizer.transform([sentence])
    prediction = model.predict(sentence_vec)
    return prediction[0]
test_sentence = "I am so sad and disappointed."
test_sentence
predict_emotion(test_sentence)

np.str_('negative')

In [23]:
Deepthi = "I am so excited for all!"
emotion = predict_emotion(Deepthi)
print("Deepthi:", Deepthi)
print("Predicted Emotion:", emotion)

Deepthi: I am so excited for all!
Predicted Emotion: positive

In [24]:
emotion = predict_emotion(Deepthi)
while True:
    Deepthi = input("Enter a sentence (or 'quit' to exit): ")
    if Deepthi.lower() == 'quit':
        break
    emotion = predict_emotion(Deepthi)
    print("Predicted Emotion:", emotion)

Predicted Emotion: neutral

In [25]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [26]:
accuracy_lr = model.score(X_test, y_test)
print("Logistic Regression Accuracy: {:.2f}".format(accuracy_lr))

Logistic Regression Accuracy: 0.61

In [27]:
Deepthi = "I am super excited about this project!"
Deepthi_vec = vectorizer.transform([clean_text(Deepthi)])
prediction = model.predict(Deepthi_vec)
print("Predicted Emotion (LR):", prediction[0])

Predicted Emotion (LR): positive

In [28]:
from sklearn.svm import LinearSVC
model_svm = LinearSVC()
model_svm.fit(X_train, y_train)
accuracy_svm = model_svm.score(X_test, y_test)
print("SVM Accuracy:{:.2f}".format(accuracy_svm))

SVM Accuracy:0.61

In [29]:
Deepthi = "I feel so sad today..."
Deepthi_vec = vectorizer.transform([clean_text(Deepthi)])
prediction = model_svm.predict(Deepthi_vec)
print("Predicted Emotion (SVM):", prediction[0])

Predicted Emotion (SVM): negative

In [30]:
print("Logistic Regression Accuracy:{:.2f}".format(accuracy_lr))
print("SVM Accuracy:{:.2f}".format(accuracy_svm))

Logistic Regression Accuracy:0.61
SVM Accuracy:0.61

In [31]:
import joblib
# THIS HELPS TO SAVVE YOUR MODEL AND USE ANY METHOD LIKE NAIVE BAYES, LOGISTIC REGRESSION, SVM
joblib.dump(model_svm, "sentiment_model_svm.pkl")  
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [32]:
import joblib
# NOW MY MODEL IS READY TO PREDICT WE NEED TO RETRAIN AGAIN
model_svm = joblib.load("sentiment_model_svm.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

In [33]:
def predict_emotion(sentence):
    sentence = clean_text(sentence)                  # TO CLEAN THE SENTENCE
    sentence_vec = vectorizer.transform([sentence])  # CONVERT IN TO NUMBERS
    prediction = model_svm.predict(sentence_vec)     # PREDICT EMOTION BY GIVEN SENTENCE
    return prediction[0]

#  TEST THE MODEL
tweet = "I am very happy today!"
print("Predicted Emotion:", predict_emotion(tweet))

Predicted Emotion: positive